package west_bank_ejec;

import javax.swing.JOptionPane;
import java.util.logging.Logger;
import west_bank_ejec.ClienteDAO;


public class Registro extends javax.swing.JFrame {

    private Banco banco;
    private static final Logger logger = Logger.getLogger(Registro.class.getName());

    public Registro(Banco banco) {
        initComponents();
        this.banco = banco;
    }





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jDialog1 = new javax.swing.JDialog();
        jFrame1 = new javax.swing.JFrame();
        jMenuItem1 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu1 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtRutT = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtNombreT = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        txtApellidoPaternoT = new javax.swing.JLabel();
        txtApellidoPaterno = new javax.swing.JTextField();
        txtApellidoMaternoT = new javax.swing.JLabel();
        txtTelefonoT = new javax.swing.JLabel();
        txtCuentaT = new javax.swing.JLabel();
        txtApellidoMaterno = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtComuna = new javax.swing.JTextField();
        cbbCuenta = new javax.swing.JComboBox<>();
        txtComunaT = new javax.swing.JLabel();
        txtDomicilioT = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDomicilio = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenuItem1.setText("jMenuItem1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 328, 214, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("Actions.Blue")), "Registro de Clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semibold", 0, 14))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(153, 204, 255));
        jPanel2.setToolTipText("");
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtRutT.setText("Rut");
        jPanel2.add(txtRutT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 39, 113, -1));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 61, 150, -1));

        txtNombreT.setText("Nombre");
        jPanel2.add(txtNombreT, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 39, -1, -1));

        txtRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutActionPerformed(evt);
            }
        });
        jPanel2.add(txtRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 61, 150, -1));

        txtApellidoPaternoT.setText("Apellido Paterno");
        jPanel2.add(txtApellidoPaternoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 39, 128, -1));
        jPanel2.add(txtApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 61, 150, -1));

        txtApellidoMaternoT.setText("Apellido Materno");
        jPanel2.add(txtApellidoMaternoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 131, -1, -1));

        txtTelefonoT.setText("Telefono");
        jPanel2.add(txtTelefonoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 131, 113, -1));

        txtCuentaT.setText("Cuenta");
        jPanel2.add(txtCuentaT, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 131, 128, -1));
        jPanel2.add(txtApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 153, 150, -1));
        jPanel2.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 153, 150, -1));
        jPanel2.add(txtComuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 150, -1));

        cbbCuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuenta Corriente", "Cuenta de Ahorro" }));
        cbbCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbCuentaActionPerformed(evt);
            }
        });
        jPanel2.add(cbbCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 153, 150, -1));

        txtComunaT.setText("Comuna");
        jPanel2.add(txtComunaT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        txtDomicilioT.setText("Domicilio");
        jPanel2.add(txtDomicilioT, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        jLabel3.setText("Numero");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 150, -1));

        txtDomicilio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDomicilioActionPerformed(evt);
            }
        });
        jPanel2.add(txtDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 150, -1));

        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });
        jPanel2.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 150, -1));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 314, 200, 38));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 620, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutActionPerformed

    }//GEN-LAST:event_txtRutActionPerformed

    private void txtDomicilioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDomicilioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDomicilioActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

    String rut = txtRut.getText().trim();
    String nombre = txtNombre.getText().trim();
    String apellidoPaterno = txtApellidoPaterno.getText().trim();
    String apellidoMaterno = txtApellidoMaterno.getText().trim();
    String telefonoStr = txtTelefono.getText().trim();
    String TipoCuenta = cbbCuenta.getSelectedItem().toString();
    String comuna = txtComuna.getText().trim();
    String domicilio = txtDomicilio.getText().trim();
    String numeroCuentaStr = txtNumero.getText().trim();
    
    if (rut.isEmpty() || nombre.isEmpty() || apellidoPaterno.isEmpty() || apellidoMaterno.isEmpty() ||
    telefonoStr.isEmpty() || TipoCuenta.isEmpty() || comuna.isEmpty() || domicilio.isEmpty() || numeroCuentaStr.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Debes completar todos los datos primero.");
    return;
    }
    
    int telefono;
    int numeroCuenta;
    try {
        telefono = Integer.parseInt(telefonoStr);
        numeroCuenta = Integer.parseInt(numeroCuentaStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Teléfono y número de cuenta deben ser números válidos.");
        return;
    }
    
    if (rut.length() < 11 || rut.length() > 12) {
        JOptionPane.showMessageDialog(this, "El RUT debe tener entre 11 y 12 caracteres.");
        return;
    }


    CuentaBancaria cuenta;
    if (TipoCuenta.equalsIgnoreCase("Cuenta Corriente")) {
        cuenta = new CuentaCorriente(numeroCuenta);
    } else if (TipoCuenta.equalsIgnoreCase("Cuenta de Ahorro")) {
        cuenta = new CuentaAhorro(numeroCuenta);
    } else {
        JOptionPane.showMessageDialog(this, "Tipo de cuenta inválido.");
        return;
    }

    Cliente nuevoCliente = new Cliente(rut, nombre, apellidoPaterno, apellidoMaterno, domicilio, comuna, telefono, TipoCuenta, cuenta);
    ClienteDAO clienteDAO = new ClienteDAO();

    boolean guardado = clienteDAO.guardarCliente(nuevoCliente);
    if (guardado) {
        JOptionPane.showMessageDialog(this, "Cliente registrado exitosamente en la base de datos.");
        banco.agregarCliente(nuevoCliente);  
    } else {
       JOptionPane.showMessageDialog(this, "Error al registrar cliente en la base de datos.");
       return; 
    }

    West_Bank_Menu menu = new West_Bank_Menu(banco);
    menu.setVisible(true);
    this.dispose();    
    
    
    txtRut.setText("");
    txtNombre.setText("");
    txtApellidoPaterno.setText("");
    txtApellidoMaterno.setText("");
    txtTelefono.setText("");
    cbbCuenta.setSelectedIndex(0);
    txtComuna.setText("");
    txtDomicilio.setText("");
    txtNumero.setText("");
}
     
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            Banco banco = new Banco();
            new Registro(banco).setVisible(true);
        });
 


    
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void cbbCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbCuentaActionPerformed
        
    }//GEN-LAST:event_cbbCuentaActionPerformed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbbCuenta;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JLabel txtApellidoMaternoT;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JLabel txtApellidoPaternoT;
    private javax.swing.JTextField txtComuna;
    private javax.swing.JLabel txtComunaT;
    private javax.swing.JLabel txtCuentaT;
    private javax.swing.JTextField txtDomicilio;
    private javax.swing.JLabel txtDomicilioT;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JLabel txtNombreT;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRut;
    private javax.swing.JLabel txtRutT;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JLabel txtTelefonoT;
    // End of variables declaration//GEN-END:variables
}